### ISSUE TITLE
JSON-RPC

### ISSUE THREAD

**Issue by jonisb** [jonisb/KodiEventGhost#10]
- [ ] Notifications
- [ ] Methods
  - [ ]   TCP
  - [ ]   HTTP

- [ ] Create JSON-RPC event when loosing connection to Kodi #5 
- [ ] JSON-RPC methods return value in event as alternative #11 
- [ ] JSON-RPC GUI config parameter layout #13
